# Use the official slim Python 3.12 base image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /inventory_management_system

# Copy the rest of the application code
COPY . /inventory_management_system/

# Set the default command to run the application
CMD ["python3.12", "app.py"]
